# -*- coding: utf-8 -*-
"""Untitled43.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ON4ZetbdwrF5DosGQd0VUi_7farRlr0
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df =pd.read_csv("/content/drive/MyDrive/Colab Notebooks/AAPL.csv")
df

avg_open = df['Open'].mean()
avg_close = df['Close'].mean()

print(f"Average Open Price:  ${avg_open:.2f}")
print(f"Average Close Price: ${avg_close:.2f}")

print(df.describe())

df["Daily_Price"] = df["Close"] - df["Open"]

df['Daily Return'] = (
    (df['Close'] - df['Open'])/ df['Open']
    )*100

print (df [["Date","Open","Close","Daily_Price","Daily Return"]
           ].head(10))

average_volume = df["Volume"].mean()
maximum_volume = df["Volume"].max()
minimum_volume = df["Volume"].min()

print(f"Average Volume: {average_volume:.2f}")
print(f"Maximum Volume: {maximum_volume}")
print(f"Minimum Volume: {minimum_volume}")



